// Theme presets + font options for the Design Studio.
// Each preset overrides the palette tokens in client-config.js. Cass picks one
// (or stays on default) and every email re-themes automatically.

export const THEME_PRESETS = {
  espresso: {
    id: 'espresso',
    name: 'Editorial Espresso',
    description: 'Dark editorial — espresso bg, cream accent. The current default.',
    palette: {
      bg:         '#15110d',
      surface:    '#1d1814',
      surfaceAlt: '#25201b',
      border:     '#332c26',
      borderSoft: '#2a2420',
      text:       '#f4ecdf',
      textSoft:   '#ddd2c0',
      muted:      '#948a7c',
      accent:     '#c9b9a5',
      ctaBg:      '#f4ecdf',
      ctaFg:      '#15110d',
    },
    swatches: ['#15110d', '#c9b9a5', '#f4ecdf'],
  },
  cream: {
    id: 'cream',
    name: 'Cream Salon',
    description: 'Light, airy, magazine — espresso text on a warm cream canvas.',
    palette: {
      bg:         '#FAF7F2',
      surface:    '#FFFFFF',
      surfaceAlt: '#F5F0E8',
      border:     '#E5DFD3',
      borderSoft: '#EFE9DC',
      text:       '#15110d',
      textSoft:   '#3D2E22',
      muted:      '#8A7A66',
      accent:     '#15110d',
      ctaBg:      '#15110d',
      ctaFg:      '#FAF7F2',
    },
    swatches: ['#FAF7F2', '#15110d', '#8A7A66'],
  },
  mono: {
    id: 'mono',
    name: 'Stone Mono',
    description: 'Pure neutral — graphite text on warm white. Quietly luxurious.',
    palette: {
      bg:         '#F5F2ED',
      surface:    '#FFFFFF',
      surfaceAlt: '#EFEAE2',
      border:     '#D9D2C5',
      borderSoft: '#E5DFD3',
      text:       '#1A1A1A',
      textSoft:   '#3A3A3A',
      muted:      '#8A8580',
      accent:     '#2D2D2D',
      ctaBg:      '#1A1A1A',
      ctaFg:      '#F5F2ED',
    },
    swatches: ['#F5F2ED', '#1A1A1A', '#8A8580'],
  },
  gold: {
    id: 'gold',
    name: 'Gold Salon',
    description: 'Espresso with a metallic gold accent. Highest-end feel.',
    palette: {
      bg:         '#15110d',
      surface:    '#1d1814',
      surfaceAlt: '#28201a',
      border:     '#3a2f24',
      borderSoft: '#2e2620',
      text:       '#f4ecdf',
      textSoft:   '#dcc9a8',
      muted:      '#a08c70',
      accent:     '#C8A56A',
      ctaBg:      '#C8A56A',
      ctaFg:      '#15110d',
    },
    swatches: ['#15110d', '#C8A56A', '#f4ecdf'],
  },
  editorial: {
    id: 'editorial',
    name: 'Pure Editorial',
    description: 'High-contrast museum monochrome. Confident, minimal.',
    palette: {
      bg:         '#000000',
      surface:    '#0a0a0a',
      surfaceAlt: '#161616',
      border:     '#2a2a2a',
      borderSoft: '#1a1a1a',
      text:       '#FFFFFF',
      textSoft:   '#D4D4D4',
      muted:      '#888888',
      accent:     '#FFFFFF',
      ctaBg:      '#FFFFFF',
      ctaFg:      '#000000',
    },
    swatches: ['#000000', '#FFFFFF', '#888888'],
  },
};

export const DISPLAY_FONTS = {
  'dm-serif': {
    id: 'dm-serif',
    name: 'DM Serif Display',
    description: 'Modern editorial. The current default.',
    family: "'DM Serif Display', Georgia, serif",
    googleFamily: 'DM+Serif+Display:ital@0;1',
  },
  'cormorant': {
    id: 'cormorant',
    name: 'Cormorant Garamond',
    description: 'Elegant, classical, magazine cover.',
    family: "'Cormorant Garamond', Georgia, serif",
    googleFamily: 'Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400',
  },
  'playfair': {
    id: 'playfair',
    name: 'Playfair Display',
    description: 'High-contrast serif, statement-making.',
    family: "'Playfair Display', Georgia, serif",
    googleFamily: 'Playfair+Display:ital,wght@0,400;0,600;0,700;1,400',
  },
  'crimson': {
    id: 'crimson',
    name: 'Crimson Pro',
    description: 'Soft, literary, less dramatic.',
    family: "'Crimson Pro', Georgia, serif",
    googleFamily: 'Crimson+Pro:ital,wght@0,400;0,500;0,600;1,400',
  },
};

export const BODY_FONTS = {
  'dm-sans': {
    id: 'dm-sans',
    name: 'DM Sans',
    description: 'Clean, modern, neutral. The current default.',
    family: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
    googleFamily: 'DM+Sans:wght@400;500;600',
  },
  'inter': {
    id: 'inter',
    name: 'Inter',
    description: 'Slightly more technical, lower-contrast.',
    family: "'Inter', system-ui, sans-serif",
    googleFamily: 'Inter:wght@400;500;600',
  },
};
